FROM python:3.12-bookworm
RUN apt-get update && apt-get install -y jq
RUN pip install poetry==1.4.2
WORKDIR /app
COPY pyproject.toml poetry.lock* /app/
RUN poetry install --no-root
COPY . .
RUN chmod +x dev-init-docker.sh
ENTRYPOINT ["./dev-init-docker.sh"]
