volumes:
  keycloak_data: {}
  vlm_data: {}
  redis-data: {}

networks:
  ls:
    ipam:
      config:
        # Specify the subnet range for IP address allocation
        - subnet: 10.0.2.0/24

services:
  keycloak-db:
    image: postgres:17.6
    container_name: keycloak-db
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    networks:
      - ls

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: postgres
      DB_ADDR: keycloak-db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
    depends_on:
      keycloak-db:
        condition: service_healthy
    command: 
      - start-dev
      - --http-port=9090
      - --hostname=keycloak
      - --hostname-port=9090
      - --hostname-strict-backchannel=true
      - --import-realm
    ports:
      - "9090:9090"
    networks:
      - ls
    volumes:
      - ./env-prep/realm-export.json:/opt/keycloak/data/import/realm-import.json

  virtual-lab-db:
    image: postgres:17.6
    container_name: vlm-db
    environment:
      POSTGRES_USER: vlm
      POSTGRES_PASSWORD: vlm
      POSTGRES_DB: vlm
    ports:
      - 15432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vlm"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    volumes:
      - vlm_data:/var/lib/postgresql/data
    networks:
      - ls

  mailpit:
    image: axllent/mailpit
    container_name: test-mail-server
    restart: always
    volumes:
      - ./env-prep/email-data:/email-data
    ports:
      - 8025:8025 # UI to see sent emails
      - 1025:1025 # test smtp server
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /email-data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1


  stripe-cli:
    image: stripe/stripe-cli:latest
    container_name: stripe
    environment:
      STRIPE_CLI_TELEMETRY_OPTOUT: 1
      STRIPE_API_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_DEVICE_NAME: ${STRIPE_DEVICE_NAME}
    entrypoint:
      - '/bin/sh'
      - '-c'
      - stripe listen --forward-to http://host.docker.internal:8000/payments/webhook
    network_mode: host
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "172.17.0.1:host-gateway"

  redis:
    image: "redis:7.2.3"
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./env-prep/init/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s