"""Add unique constraint on github_file_url per project

Revision ID: 012d58ed355a
Revises: 7c1fb4ac58c9
Create Date: 2025-02-03 16:48:59.132838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '012d58ed355a'
down_revision: Union[str, None] = '7c1fb4ac58c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('notebook_github_file_url_key', 'notebook', type_='unique')
    op.create_unique_constraint('uq_project_file_url', 'notebook', ['project_id', 'github_file_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_project_file_url', 'notebook', type_='unique')
    op.create_unique_constraint('notebook_github_file_url_key', 'notebook', ['github_file_url'])
    # ### end Alembic commands ###
