"""cleanup nexus

Revision ID: 0af36743e9f3
Revises: 0a629d99201a
Create Date: 2025-07-04 22:07:05.616334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0af36743e9f3'
down_revision: Union[str, None] = '0a629d99201a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('project_nexus_project_id_key', 'project', type_='unique')
    op.drop_column('project', 'nexus_project_id')
    op.drop_constraint('virtual_lab_nexus_organization_id_key', 'virtual_lab', type_='unique')
    op.drop_column('virtual_lab', 'nexus_organization_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('virtual_lab', sa.Column('nexus_organization_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('virtual_lab_nexus_organization_id_key', 'virtual_lab', ['nexus_organization_id'])
    op.add_column('project', sa.Column('nexus_project_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('project_nexus_project_id_key', 'project', ['nexus_project_id'])
    # ### end Alembic commands ###
