"""add_credit_value_to_seat

Revision ID: 10e0d7bf4813
Revises: 2c590c5cbe3a
Create Date: 2026-06-09 03:57:08.762540

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "10e0d7bf4813"
down_revision: Union[str, None] = "2c590c5cbe3a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("seat", sa.Column("credit_value", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("seat", "credit_value")
    # ### end Alembic commands ###
