"""subscription plans

Revision ID: 1849f8159098
Revises: 2b3c5dda598e
Create Date: 2025-03-06 06:25:36.863390

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1849f8159098"
down_revision: Union[str, None] = "2b3c5dda598e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscription_plan",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("stripe_product_id", sa.String(length=255), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("sanity_id", sa.String(length=255), nullable=True),
        sa.Column("stripe_monthly_price_id", sa.String(length=255), nullable=True),
        sa.Column("monthly_amount", sa.Integer(), nullable=False),
        sa.Column("stripe_yearly_price_id", sa.String(length=255), nullable=True),
        sa.Column("yearly_amount", sa.Integer(), nullable=False),
        sa.Column("features", sa.JSON(), nullable=True),
        sa.Column("plan_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("stripe_product_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("subscription_plan")
    # ### end Alembic commands ###
