"""subscription inheritance

Revision ID: 239868dc46e3
Revises: a028678c911b
Create Date: 2025-03-05 16:06:24.784589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "239868dc46e3"
down_revision: Union[str, None] = "a028678c911b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "free_subscription",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["subscription.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "paid_subscription",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("stripe_subscription_id", sa.String(length=255), nullable=False),
        sa.Column("stripe_price_id", sa.String(length=255), nullable=False),
        sa.Column("customer_id", sa.String(length=255), nullable=False),
        sa.Column("cancel_at_period_end", sa.Boolean(), nullable=False),
        sa.Column("canceled_at", sa.DateTime(), nullable=True),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("billing_cycle_anchor", sa.DateTime(), nullable=True),
        sa.Column("default_payment_method", sa.String(length=255), nullable=True),
        sa.Column("latest_invoice", sa.String(length=255), nullable=True),
        sa.Column("auto_renew", sa.Boolean(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("interval", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["subscription.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_paid_subscription_customer_id"),
        "paid_subscription",
        ["customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_paid_subscription_stripe_subscription_id"),
        "paid_subscription",
        ["stripe_subscription_id"],
        unique=True,
    )
    op.add_column(
        "subscription",
        sa.Column("subscription_type", sa.String(length=50), nullable=False),
    )
    op.add_column(
        "subscription", sa.Column("type", sa.String(length=50), nullable=False)
    )
    op.drop_index("ix_subscription_customer_id", table_name="subscription")
    op.drop_index("ix_subscription_stripe_subscription_id", table_name="subscription")
    op.drop_column("subscription", "currency")
    op.drop_column("subscription", "interval")
    op.drop_column("subscription", "default_payment_method")
    op.drop_column("subscription", "customer_id")
    op.drop_column("subscription", "ended_at")
    op.drop_column("subscription", "amount")
    op.drop_column("subscription", "stripe_subscription_id")
    op.drop_column("subscription", "canceled_at")
    op.drop_column("subscription", "stripe_price_id")
    op.drop_column("subscription", "latest_invoice")
    op.drop_column("subscription", "auto_renew")
    op.drop_column("subscription", "billing_cycle_anchor")
    op.drop_column("subscription", "cancel_at_period_end")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subscription",
        sa.Column(
            "cancel_at_period_end", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "subscription",
        sa.Column(
            "billing_cycle_anchor",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "subscription",
        sa.Column("auto_renew", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "subscription",
        sa.Column(
            "latest_invoice", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "subscription",
        sa.Column(
            "stripe_price_id",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "subscription",
        sa.Column(
            "canceled_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "subscription",
        sa.Column(
            "stripe_subscription_id",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "subscription",
        sa.Column("amount", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "subscription",
        sa.Column(
            "ended_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "subscription",
        sa.Column(
            "customer_id", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "subscription",
        sa.Column(
            "default_payment_method",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "subscription",
        sa.Column(
            "interval", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "subscription",
        sa.Column(
            "currency", sa.VARCHAR(length=3), autoincrement=False, nullable=False
        ),
    )
    op.create_index(
        "ix_subscription_stripe_subscription_id",
        "subscription",
        ["stripe_subscription_id"],
        unique=True,
    )
    op.create_index(
        "ix_subscription_customer_id", "subscription", ["customer_id"], unique=False
    )
    op.drop_column("subscription", "type")
    op.drop_column("subscription", "subscription_type")
    op.drop_index(
        op.f("ix_paid_subscription_stripe_subscription_id"),
        table_name="paid_subscription",
    )
    op.drop_index(
        op.f("ix_paid_subscription_customer_id"), table_name="paid_subscription"
    )
    op.drop_table("paid_subscription")
    op.drop_table("free_subscription")
    # ### end Alembic commands ###
