"""fix customer name in StripeUser

Revision ID: 294486398197
Revises: 3c929ac345d4
Create Date: 2025-03-11 14:02:06.473190

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "294486398197"
down_revision: Union[str, None] = "3c929ac345d4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stripe_user",
        sa.Column("stripe_customer_id", sa.String(length=255), nullable=False),
    )
    op.drop_constraint(
        "stripe_user_stripe_costumer_id_key", "stripe_user", type_="unique"
    )
    op.create_unique_constraint(
        "stripe_user_stripe_customer_id_key", "stripe_user", ["stripe_customer_id"]
    )
    op.drop_column("stripe_user", "stripe_costumer_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stripe_user",
        sa.Column(
            "stripe_costumer_id",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(
        "stripe_user_stripe_customer_id_key", "stripe_user", type_="unique"
    )
    op.create_unique_constraint(
        "stripe_user_stripe_costumer_id_key", "stripe_user", ["stripe_costumer_id"]
    )
    op.drop_column("stripe_user", "stripe_customer_id")
    # ### end Alembic commands ###
