"""fix_nullable_columns

Revision ID: 2a8e7c720792
Revises: 3b4875eae5d9
Create Date: 2025-09-05 08:52:55.789004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2a8e7c720792"
down_revision: Union[str, None] = "3b4875eae5d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "project", "name", existing_type=sa.VARCHAR(length=250), nullable=False
    )
    op.alter_column("project", "deleted", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column(
        "project", "virtual_lab_id", existing_type=sa.UUID(), nullable=False
    )
    op.alter_column(
        "virtual_lab", "name", existing_type=sa.VARCHAR(length=250), nullable=False
    )
    op.alter_column(
        "virtual_lab", "deleted", existing_type=sa.BOOLEAN(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("virtual_lab", "deleted", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column(
        "virtual_lab", "name", existing_type=sa.VARCHAR(length=250), nullable=True
    )
    op.alter_column("project", "virtual_lab_id", existing_type=sa.UUID(), nullable=True)
    op.alter_column("project", "deleted", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column(
        "project", "name", existing_type=sa.VARCHAR(length=250), nullable=True
    )
    # ### end Alembic commands ###
