"""add customer id to payment

Revision ID: 2b3c5dda598e
Revises: 239868dc46e3
Create Date: 2025-03-05 18:13:45.636133

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2b3c5dda598e"
down_revision: Union[str, None] = "239868dc46e3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subscription_payment",
        sa.Column("customer_id", sa.String(length=255), nullable=False),
    )
    op.create_index(
        op.f("ix_subscription_payment_customer_id"),
        "subscription_payment",
        ["customer_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_subscription_payment_customer_id"), table_name="subscription_payment"
    )
    op.drop_column("subscription_payment", "customer_id")
    # ### end Alembic commands ###
