"""add_created_at_to_seat

Revision ID: 2c590c5cbe3a
Revises: ff9173c91b7c
Create Date: 2026-06-08 21:39:03.033663

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2c590c5cbe3a"
down_revision: Union[str, None] = "ff9173c91b7c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "seat", sa.Column("created_at", sa.DateTime(timezone=True), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("seat", "created_at")
    # ### end Alembic commands ###
