"""add subscription source

Revision ID: 2dd76784caea
Revises: cb970364cd2a
Create Date: 2025-04-18 12:35:46.328185

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2dd76784caea"
down_revision: Union[str, None] = "cb970364cd2a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

subscription_source_enum = sa.Enum("API", "SCRIPT", "SQL", name="subscriptionsource")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    subscription_source_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "subscription",
        sa.Column(
            "source",
            subscription_source_enum,
            nullable=False,
            server_default="API",  # Set default value at DB level
            index=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_subscription_source"), table_name="subscription")
    op.drop_column("subscription", "source")
    # ### end Alembic commands ###
