"""project default value is 0

Revision ID: 325c166bfe76
Revises: 43f3dc1937d7
Create Date: 2024-05-15 17:32:09.520300

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.orm import Session

from alembic import op
from virtual_labs.infrastructure.db.models import Project

# revision identifiers, used by Alembic.
revision: str = "325c166bfe76"
down_revision: Union[str, None] = "43f3dc1937d7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    session = Session(bind=conn)
    session.execute(statement=sa.update(Project).values(budget=0))
    session.commit()
    op.alter_column(
        "project",
        "budget",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Integer(),
        nullable=False,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "project",
        "budget",
        existing_type=sa.Integer(),
        type_=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    # ### end Alembic commands ###
