"""remove notebook table and related migrations

Revision ID: 3296b75fc5a1
Revises: c615148b3cf7
Create Date: 2025-11-20 10:19:37.336513

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3296b75fc5a1"
down_revision: Union[str, None] = "c615148b3cf7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_notebook_project_id"), table_name="notebook")
    op.drop_table("notebook")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notebook",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("github_file_url", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("github_file_url", name="notebook_github_file_url_key"),
    )
    op.create_index(
        op.f("ix_notebook_project_id"), "notebook", ["project_id"], unique=False
    )
    op.drop_constraint("notebook_github_file_url_key", "notebook", type_="unique")
    op.create_unique_constraint(
        "uq_project_file_url", "notebook", ["project_id", "github_file_url"]
    )
    # ### end Alembic commands ###
