"""add user preference logic

Revision ID: 3b4875eae5d9
Revises: 0af36743e9f3
Create Date: 2025-09-04 17:42:43.901724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3b4875eae5d9"
down_revision: Union[str, None] = "0af36743e9f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_preference",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("virtual_lab_id", sa.UUID(), nullable=True),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
        sa.ForeignKeyConstraint(
            ["virtual_lab_id"],
            ["virtual_lab.id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index(
        op.f("ix_user_preference_project_id"),
        "user_preference",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_preference_virtual_lab_id"),
        "user_preference",
        ["virtual_lab_id"],
        unique=False,
    )
    op.create_index(
        "ix_user_preference_workspace",
        "user_preference",
        ["virtual_lab_id", "project_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_preference_workspace", table_name="user_preference")
    op.drop_index(
        op.f("ix_user_preference_virtual_lab_id"), table_name="user_preference"
    )
    op.drop_index(op.f("ix_user_preference_project_id"), table_name="user_preference")
    op.drop_table("user_preference")
    # ### end Alembic commands ###
