"""add_credits_per_seat_to_course

Revision ID: 4bebe19540f0
Revises: 10e0d7bf4813
Create Date: 2026-06-09 04:36:40.973765

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4bebe19540f0"
down_revision: Union[str, None] = "10e0d7bf4813"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("course", sa.Column("credits_per_seat", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("course", "credits_per_seat")
    # ### end Alembic commands ###
