"""Add notebook table

Revision ID: 4c6f1051dc93
Revises: 981da98985c0
Create Date: 2025-01-31 19:00:02.717145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4c6f1051dc93"
down_revision: Union[str, None] = "981da98985c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notebook",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("github_file_url", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("github_file_url"),
    )
    op.create_index(
        op.f("ix_notebook_project_id"), "notebook", ["project_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_notebook_project_id"), table_name="notebook")
    op.drop_table("notebook")
    # ### end Alembic commands ###
