"""add card_exp property to subscription payment

Revision ID: 4f998a94cbbc
Revises: a39935cc0b0b
Create Date: 2025-03-05 11:04:26.593538

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4f998a94cbbc"
down_revision: Union[str, None] = "a39935cc0b0b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscription_payment", "cardholder_name")
    op.drop_column("subscription_payment", "stripe_metadata")
    op.drop_column("subscription_payment", "cardholder_email")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subscription_payment",
        sa.Column(
            "cardholder_email",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "subscription_payment",
        sa.Column(
            "stripe_metadata",
            postgresql.JSON(astext_type=sa.Text()),  # type: ignore
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "subscription_payment",
        sa.Column(
            "cardholder_name",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
