"""Bookmarks for resource unique per project and category

Revision ID: 5242355ed15d
Revises: 2cd64f276718
Create Date: 2024-06-06 16:03:26.466944

"""
from typing import Sequence, Union

from alembic import op

revision: str = "5242355ed15d"
down_revision: Union[str, None] = "7c0ed751c6d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "bookmark_unique_for_resource_category_per_project",
        "bookmark",
        ["resource_id", "category", "project_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "bookmark_unique_for_resource_category_per_project", "bookmark", type_="unique"
    )
    # ### end Alembic commands ###
