"""remove_budget_from_vlab

Revision ID: 56ad6da93b9c
Revises: dea5531bc9dc
Create Date: 2024-05-13 15:46:03.189120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "56ad6da93b9c"
down_revision: Union[str, None] = "dea5531bc9dc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("virtual_lab", "budget")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "virtual_lab",
        sa.Column(
            "budget",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
