"""Add unique constraint on github_file_url per project

Revision ID: 5900df67288c
Revises: 7c1fb4ac58c9
Create Date: 2025-02-03 12:34:33.482156

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "5900df67288c"
down_revision: Union[str, None] = "7c1fb4ac58c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("notebook_github_file_url_key", "notebook", type_="unique")
    op.create_unique_constraint(
        "uix_project_github_file_url", "notebook", ["project_id", "github_file_url"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uix_project_github_file_url", "notebook", type_="unique")
    op.create_unique_constraint(
        "notebook_github_file_url_key", "notebook", ["github_file_url"]
    )
    # ### end Alembic commands ###
