"""standalone payment attach to vlab

Revision ID: 62216ef51974
Revises: 294486398197
Create Date: 2025-03-15 14:33:02.539460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "62216ef51974"
down_revision: Union[str, None] = "294486398197"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "subscription_payment", "virtual_lab_id", existing_type=sa.UUID(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "subscription_payment",
        "virtual_lab_id",
        existing_type=sa.UUID(),
        nullable=False,
    )
    # ### end Alembic commands ###
