"""add payment_method table

Revision ID: 6338b6ac5353
Revises: aa81eeb4dad6
Create Date: 2024-05-03 14:59:19.487353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6338b6ac5353'
down_revision: Union[str, None] = 'aa81eeb4dad6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_method',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stripe_payment_method_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('customerId', sa.String(), nullable=False),
    sa.Column('card_number', sa.String(length=4), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('cardholder_name', sa.String(), nullable=False),
    sa.Column('cardholder_email', sa.String(), nullable=False),
    sa.Column('expire_at', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('virtual_lab_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['virtual_lab_id'], ['virtual_lab.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_method')
    # ### end Alembic commands ###
