"""vlm migration

Revision ID: 6517ad801bf6
Revises: 93c9ff52845c
Create Date: 2025-04-15 17:08:45.779960

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6517ad801bf6"
down_revision: Union[str, None] = "93c9ff52845c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("bookmark", "entity_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("bookmark", "entity_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
