"""add budget_amount to project

Revision ID: 69985dd88e88
Revises: 43f3dc1937d7
Create Date: 2024-05-16 17:38:37.669754

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.orm import Session

from alembic import op
from virtual_labs.infrastructure.db.models import Project

# revision identifiers, used by Alembic.
revision: str = "69985dd88e88"
down_revision: Union[str, None] = "43f3dc1937d7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    session = Session(bind=conn)
    op.add_column(
        "project",
        sa.Column("budget_amount", sa.Integer(), nullable=True, server_default="0"),
    )

    for (id,) in session.query(Project.id):
        budget = session.execute(
            sa.text("SELECT budget FROM project WHERE id = :id"), {"id": id}
        ).scalar_one()
        session.execute(
            statement=sa.update(Project)
            .where(Project.id == id)
            .values(budget_amount=0 if budget is None else budget)
        )
    session.commit()
    op.alter_column(table_name="project", column_name="budget_amount", nullable=False)
    op.drop_column("project", "budget")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project",
        sa.Column(
            "budget",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("project", "budget_amount")
    # ### end Alembic commands ###
