"""add table for email verification sessions history -only-audit

Revision ID: 6c62a8fe7a4c
Revises: ee06c49abcad
Create Date: 2026-03-19 12:59:07.943054

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6c62a8fe7a4c"
down_revision: Union[str, None] = "ee06c49abcad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_verification",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("virtual_lab_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("code", sa.String(length=6), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["virtual_lab_id"],
            ["virtual_lab.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_email_verif_user_email",
        "email_verification",
        ["user_id", "email", "verified"],
        unique=False,
    )
    op.create_index(
        "ix_email_verif_user_lab",
        "email_verification",
        ["user_id", "virtual_lab_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_email_verification_email"),
        "email_verification",
        ["email"],
        unique=False,
    )
    op.create_index(
        op.f("ix_email_verification_user_id"),
        "email_verification",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_email_verification_verified"),
        "email_verification",
        ["verified"],
        unique=False,
    )
    op.create_index(
        op.f("ix_email_verification_virtual_lab_id"),
        "email_verification",
        ["virtual_lab_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_email_verification_virtual_lab_id"), table_name="email_verification"
    )
    op.drop_index(
        op.f("ix_email_verification_verified"), table_name="email_verification"
    )
    op.drop_index(
        op.f("ix_email_verification_user_id"), table_name="email_verification"
    )
    op.drop_index(op.f("ix_email_verification_email"), table_name="email_verification")
    op.drop_index("ix_email_verif_user_lab", table_name="email_verification")
    op.drop_index("ix_email_verif_user_email", table_name="email_verification")
    op.drop_table("email_verification")
    # ### end Alembic commands ###
