"""Vlabs index

Revision ID: 6fec61d361a4
Revises: 981da98985c0
Create Date: 2024-09-30 03:27:18.599363

"""

from typing import Sequence, Union

import sqlalchemy as sa  # noqa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6fec61d361a4"
down_revision: Union[str, None] = "981da98985c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_virtual_lab_deleted", table_name="virtual_lab")
    op.drop_constraint("unique_admin_group_id_for_lab", "virtual_lab", type_="unique")
    op.drop_constraint("unique_member_group_id_for_lab", "virtual_lab", type_="unique")
    op.create_index(
        op.f("ix_virtual_lab_admin_group_id"),
        "virtual_lab",
        ["admin_group_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_virtual_lab_member_group_id"),
        "virtual_lab",
        ["member_group_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_virtual_lab_member_group_id"), table_name="virtual_lab")
    op.drop_index(op.f("ix_virtual_lab_admin_group_id"), table_name="virtual_lab")
    op.create_unique_constraint(
        "unique_member_group_id_for_lab", "virtual_lab", ["member_group_id"]
    )
    op.create_unique_constraint(
        "unique_admin_group_id_for_lab", "virtual_lab", ["admin_group_id"]
    )
    op.create_index("ix_virtual_lab_deleted", "virtual_lab", ["deleted"], unique=False)
    # ### end Alembic commands ###
