"""unique project name per virtual lab

Revision ID: 74b8df4c5566
Revises: 2cd64f276718
Create Date: 2024-06-10 10:47:01.889416

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "74b8df4c5566"
down_revision: Union[str, None] = "2cd64f276718"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "unique_name_per_virtual_lab", "project", ["virtual_lab_id", "name"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_name_per_virtual_lab", "project", type_="unique")
    # ### end Alembic commands ###
