"""course vlab

Revision ID: 7638e5e2a43f
Revises: 806e900c5dbf
Create Date: 2026-03-23 20:28:25.120679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7638e5e2a43f'
down_revision: Union[str, None] = '806e900c5dbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('virtual_lab', sa.Column('course_template_project_id', sa.UUID(), nullable=True))
    op.add_column('virtual_lab', sa.Column('is_course_initialized', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('virtual_lab', 'is_course_initialized')
    op.drop_column('virtual_lab', 'course_template_project_id')
    # ### end Alembic commands ###
