"""unique project name per virtual lab

Revision ID: 7c0ed751c6d5
Revises: 2cd64f276718
Create Date: 2024-06-11 09:24:30.994867

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7c0ed751c6d5"
down_revision: Union[str, None] = "2cd64f276718"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "unique_name_for_non_deleted",
        table_name="project",
        postgresql_where="(NOT deleted)",
    )
    op.create_index(
        "unique_project_name_for_non_deleted",
        "project",
        ["name", "deleted", "virtual_lab_id"],
        unique=True,
        postgresql_where=sa.text("NOT deleted"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "unique_project_name_for_non_deleted",
        table_name="project",
        postgresql_where=sa.text("NOT deleted"),
    )
    op.create_index(
        "unique_name_for_non_deleted",
        "project",
        ["name", "deleted"],
        unique=True,
        postgresql_where="(NOT deleted)",
    )
    # ### end Alembic commands ###
