"""add_batch_id_to_seat

Revision ID: 7fcbd62c09db
Revises: a06a7492e4a5
Create Date: 2026-06-08 20:45:42.026875

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7fcbd62c09db"
down_revision: Union[str, None] = "a06a7492e4a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("seat", sa.Column("batch_id", sa.UUID(), nullable=False))
    op.create_index(op.f("ix_seat_batch_id"), "seat", ["batch_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_seat_batch_id"), table_name="seat")
    op.drop_column("seat", "batch_id")
    # ### end Alembic commands ###
