"""add email_verified and add email verification session audit

Revision ID: 806e900c5dbf
Revises: 2192a5aa8ba6
Create Date: 2026-03-19 14:45:05.955871

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "806e900c5dbf"
down_revision: Union[str, None] = "2192a5aa8ba6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_verification",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("virtual_lab_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("code", sa.String(length=6), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["virtual_lab_id"],
            ["virtual_lab.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_email_verif_user_email",
        "email_verification",
        ["user_id", "email", "verified"],
        unique=False,
    )
    op.create_index(
        "ix_email_verif_user_lab",
        "email_verification",
        ["user_id", "virtual_lab_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_email_verification_email"),
        "email_verification",
        ["email"],
        unique=False,
    )
    op.create_index(
        op.f("ix_email_verification_user_id"),
        "email_verification",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_email_verification_verified"),
        "email_verification",
        ["verified"],
        unique=False,
    )
    op.create_index(
        op.f("ix_email_verification_virtual_lab_id"),
        "email_verification",
        ["virtual_lab_id"],
        unique=False,
    )
    op.drop_index(
        op.f("ix_email_verification_codes_code"), table_name="email_verification_codes"
    )
    op.drop_index(
        op.f("ix_email_verification_codes_email"), table_name="email_verification_codes"
    )
    op.drop_index(
        op.f("ix_verification_codes_compound_properties"),
        table_name="email_verification_codes",
    )
    op.drop_index(
        op.f("ix_verification_codes_created_at"), table_name="email_verification_codes"
    )
    op.drop_table("email_verification_codes")
    op.add_column(
        "virtual_lab", sa.Column("email_verified", sa.Boolean(), nullable=True)
    )
    op.execute("UPDATE virtual_lab SET email_verified = TRUE")
    op.alter_column("virtual_lab", "email_verified", nullable=False)
    op.create_index(
        op.f("ix_virtual_lab_email_verified"),
        "virtual_lab",
        ["email_verified"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_virtual_lab_email_verified"), table_name="virtual_lab")
    op.drop_column("virtual_lab", "email_verified")
    op.create_table(
        "email_verification_codes",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "virtual_lab_name",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("email", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("code", sa.VARCHAR(length=6), autoincrement=False, nullable=False),
        sa.Column(
            "expires_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column("is_verified", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "verified_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.CheckConstraint(
            "code::text ~* '^[0-9]{6}$'::text", name=op.f("valid_code_check")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("email_verification_codes_pkey")),
    )
    op.create_index(
        op.f("ix_verification_codes_created_at"),
        "email_verification_codes",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_verification_codes_compound_properties"),
        "email_verification_codes",
        ["email", "code", "virtual_lab_name", "user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_email_verification_codes_email"),
        "email_verification_codes",
        ["email"],
        unique=False,
    )
    op.create_index(
        op.f("ix_email_verification_codes_code"),
        "email_verification_codes",
        ["code"],
        unique=False,
    )
    op.drop_index(
        op.f("ix_email_verification_virtual_lab_id"), table_name="email_verification"
    )
    op.drop_index(
        op.f("ix_email_verification_verified"), table_name="email_verification"
    )
    op.drop_index(
        op.f("ix_email_verification_user_id"), table_name="email_verification"
    )
    op.drop_index(op.f("ix_email_verification_email"), table_name="email_verification")
    op.drop_index("ix_email_verif_user_lab", table_name="email_verification")
    op.drop_index("ix_email_verif_user_email", table_name="email_verification")
    op.drop_table("email_verification")
    # ### end Alembic commands ###
