"""add billing quotes

Revision ID: 80f793ed56d5
Revises: b9047317ad65
Create Date: 2026-05-13 12:40:00.745094

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "80f793ed56d5"
down_revision: Union[str, None] = "b9047317ad65"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "billing_quote",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("virtual_lab_id", sa.UUID(), nullable=True),
        sa.Column(
            "flow",
            sa.Enum("STANDALONE", "SUBSCRIPTION", name="billingflow"),
            nullable=False,
        ),
        sa.Column("subscription_tier_id", sa.UUID(), nullable=True),
        sa.Column("interval", sa.String(length=50), nullable=True),
        sa.Column("subtotal", sa.Integer(), nullable=False),
        sa.Column("tax_amount", sa.Integer(), nullable=False),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "tax_behavior", sa.Enum("EXCLUSIVE", name="taxbehavior"), nullable=False
        ),
        sa.Column("tax_country", sa.String(length=2), nullable=True),
        sa.Column(
            "tax_status",
            sa.Enum(
                "CALCULATED", "NOT_APPLICABLE", "PENDING", "FAILED", name="taxstatus"
            ),
            nullable=False,
        ),
        sa.Column("billing_address_json", sa.JSON(), nullable=False),
        sa.Column("stripe_tax_calculation_id", sa.String(length=255), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["subscription_tier_id"],
            ["subscription_tier.id"],
        ),
        sa.ForeignKeyConstraint(
            ["virtual_lab_id"],
            ["virtual_lab.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_billing_quote_flow"), "billing_quote", ["flow"], unique=False
    )
    op.create_index(
        op.f("ix_billing_quote_virtual_lab_id"),
        "billing_quote",
        ["virtual_lab_id"],
        unique=False,
    )
    op.add_column(
        "subscription_payment",
        sa.Column("amount_subtotal", sa.Integer(), nullable=True),
    )
    op.add_column(
        "subscription_payment", sa.Column("amount_tax", sa.Integer(), nullable=True)
    )
    op.add_column(
        "subscription_payment", sa.Column("amount_total", sa.Integer(), nullable=True)
    )
    op.add_column(
        "subscription_payment",
        sa.Column(
            "tax_behavior", sa.Enum("EXCLUSIVE", name="taxbehavior"), nullable=True
        ),
    )
    op.add_column(
        "subscription_payment",
        sa.Column("tax_country", sa.String(length=2), nullable=True),
    )
    op.add_column(
        "subscription_payment",
        sa.Column(
            "tax_status",
            sa.Enum(
                "CALCULATED", "NOT_APPLICABLE", "PENDING", "FAILED", name="taxstatus"
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "subscription_payment",
        sa.Column("billing_address_json", sa.JSON(), nullable=True),
    )
    op.add_column(
        "subscription_payment",
        sa.Column("stripe_tax_calculation_id", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "subscription_payment", sa.Column("billing_quote_id", sa.UUID(), nullable=True)
    )
    op.add_column(
        "subscription_payment",
        sa.Column("credit_base_amount", sa.Integer(), nullable=True),
    )
    op.add_column(
        "subscription_payment",
        sa.Column("credits_purchased", sa.Integer(), nullable=True),
    )
    op.create_index(
        op.f("ix_subscription_payment_billing_quote_id"),
        "subscription_payment",
        ["billing_quote_id"],
        unique=False,
    )
    op.create_foreign_key(
        None, "subscription_payment", "billing_quote", ["billing_quote_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "subscription_payment", type_="foreignkey")
    op.drop_index(
        op.f("ix_subscription_payment_billing_quote_id"),
        table_name="subscription_payment",
    )
    op.drop_column("subscription_payment", "credits_purchased")
    op.drop_column("subscription_payment", "credit_base_amount")
    op.drop_column("subscription_payment", "billing_quote_id")
    op.drop_column("subscription_payment", "stripe_tax_calculation_id")
    op.drop_column("subscription_payment", "billing_address_json")
    op.drop_column("subscription_payment", "tax_status")
    op.drop_column("subscription_payment", "tax_country")
    op.drop_column("subscription_payment", "tax_behavior")
    op.drop_column("subscription_payment", "amount_total")
    op.drop_column("subscription_payment", "amount_tax")
    op.drop_column("subscription_payment", "amount_subtotal")
    op.drop_index(op.f("ix_billing_quote_virtual_lab_id"), table_name="billing_quote")
    op.drop_index(op.f("ix_billing_quote_flow"), table_name="billing_quote")
    op.drop_table("billing_quote")
    # ### end Alembic commands ###
