"""email verification model

Revision ID: 8830da6ee3a3
Revises: 012d58ed355a
Create Date: 2025-02-13 09:09:27.890859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8830da6ee3a3"
down_revision: Union[str, None] = "012d58ed355a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_verification_codes",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("virtual_lab_name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("code", sa.String(length=6), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("verified_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("code ~* '^[0-9]{6}$'", name="valid_code_check"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_email_verification_codes_code"),
        "email_verification_codes",
        ["code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_email_verification_codes_email"),
        "email_verification_codes",
        ["email"],
        unique=False,
    )
    op.create_index(
        "ix_verification_codes_compound_properties",
        "email_verification_codes",
        ["email", "code", "virtual_lab_name", "user_id"],
        unique=False,
    )
    op.create_index(
        "ix_verification_codes_created_at",
        "email_verification_codes",
        ["created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_verification_codes_created_at", table_name="email_verification_codes"
    )
    op.drop_index(
        "ix_verification_codes_compound_properties",
        table_name="email_verification_codes",
    )
    op.drop_index(
        op.f("ix_email_verification_codes_email"), table_name="email_verification_codes"
    )
    op.drop_index(
        op.f("ix_email_verification_codes_code"), table_name="email_verification_codes"
    )
    op.drop_table("email_verification_codes")
    # ### end Alembic commands ###
