"""add course vlab fields

Revision ID: 8c7d13972ded
Revises: 2192a5aa8ba6
Create Date: 2026-03-20 18:31:51.549762

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8c7d13972ded"
down_revision: Union[str, None] = "2192a5aa8ba6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "virtual_lab",
        sa.Column(
            "is_course_vlab",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    op.add_column(
        "virtual_lab",
        sa.Column(
            "is_course_initialized",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("virtual_lab", "is_course_initialized")
    op.drop_column("virtual_lab", "is_course_vlab")
    # ### end Alembic commands ###
