"""add credits to tiers

Revision ID: 8dbea06fbbc9
Revises: 893c59d27448
Create Date: 2025-03-20 11:29:23.793350

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8dbea06fbbc9"
down_revision: Union[str, None] = "893c59d27448"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    subscriptiontierenum = sa.Enum(
        "FREE", "PRO", "PREMIUM", name="subscriptiontierenum"
    )
    subscriptiontierenum.create(op.get_bind())  # type: ignore[no-untyped-call]

    # Then use it in the column
    op.add_column(
        "subscription_tier", sa.Column("tier", subscriptiontierenum, nullable=False)
    )
    op.add_column(
        "subscription_tier", sa.Column("monthly_credits", sa.Integer(), nullable=False)
    )
    op.add_column(
        "subscription_tier", sa.Column("yearly_credits", sa.Integer(), nullable=False)
    )
    op.create_index(
        op.f("ix_subscription_tier_tier"), "subscription_tier", ["tier"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_subscription_tier_tier"), table_name="subscription_tier")
    op.drop_column("subscription_tier", "yearly_credits")
    op.drop_column("subscription_tier", "monthly_credits")
    op.drop_column("subscription_tier", "tier")

    # Drop the enum type
    subscriptiontierenum = sa.Enum(name="subscriptiontierenum")
    subscriptiontierenum.drop(op.get_bind())  # type: ignore[no-untyped-call]
    # ### end Alembic commands ###
