"""add credits to tiers

Revision ID: 8dbea06fbbc9
Revises: 893c59d27448
Create Date: 2025-03-20 11:29:23.793350

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8dbea06fbbc9"
down_revision: Union[str, None] = "893c59d27448"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first

    # Then use it in the column
    op.add_column(
        "subscription_tier", sa.Column("monthly_credits", sa.Integer(), nullable=False)
    )
    op.add_column(
        "subscription_tier", sa.Column("yearly_credits", sa.Integer(), nullable=False)
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscription_tier", "yearly_credits")
    op.drop_column("subscription_tier", "monthly_credits")
    # ### end Alembic commands ###
