"""add credits to tiers

Revision ID: 8dbea06fbbc9
Revises: 893c59d27448
Create Date: 2025-03-20 11:29:23.793350

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy import text

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8dbea06fbbc9"
down_revision: Union[str, None] = "893c59d27448"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First add columns as nullable
    op.add_column(
        "subscription_tier", sa.Column("monthly_credits", sa.Integer(), nullable=True)
    )
    op.add_column(
        "subscription_tier", sa.Column("yearly_credits", sa.Integer(), nullable=True)
    )

    # Update credit values for each tier
    connection = op.get_bind()

    # Free tier: 100 credits per month, 100 credits per year
    connection.execute(
        text(
            """
            UPDATE subscription_tier 
            SET monthly_credits = 100, yearly_credits = 100
            WHERE tier = 'FREE'
            """
        )
    )

    # Pro tier: 50 credits per month, 650 credits per year
    connection.execute(
        text(
            """
            UPDATE subscription_tier 
            SET monthly_credits = 50, yearly_credits = 650
            WHERE tier = 'PRO'
            """
        )
    )

    # Premium tier: 0 credits per month, 0 credits per year
    connection.execute(
        text(
            """
            UPDATE subscription_tier 
            SET monthly_credits = 0, yearly_credits = 0
            WHERE tier = 'PREMIUM'
            """
        )
    )

    # Now make the columns non-nullable
    op.alter_column("subscription_tier", "monthly_credits", nullable=False)
    op.alter_column("subscription_tier", "yearly_credits", nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscription_tier", "yearly_credits")
    op.drop_column("subscription_tier", "monthly_credits")
    # ### end Alembic commands ###
