"""remove metadata fields to subscription

Revision ID: a028678c911b
Revises: 4f998a94cbbc
Create Date: 2025-03-05 11:18:35.069342

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a028678c911b"
down_revision: Union[str, None] = "4f998a94cbbc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscription", "stripe_metadata")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subscription",
        sa.Column(
            "stripe_metadata",
            postgresql.JSON(astext_type=sa.Text()),  # type: ignore
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
