"""add onboarding_progress to user_preference

Revision ID: a114577ba18b
Revises: 3296b75fc5a1
Create Date: 2025-11-29 15:53:59.331802

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a114577ba18b"
down_revision: Union[str, None] = "3296b75fc5a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_preference",
        sa.Column(
            "onboarding_progress", sa.JSON(), server_default="{}", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_preference", "onboarding_progress")
    # ### end Alembic commands ###
