"""add card details to payment

Revision ID: a39935cc0b0b
Revises: eed2b128495f
Create Date: 2025-03-05 09:03:06.147048

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a39935cc0b0b"
down_revision: Union[str, None] = "eed2b128495f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subscription_payment",
        sa.Column("card_brand", sa.String(length=50), nullable=False),
    )
    op.add_column(
        "subscription_payment",
        sa.Column("card_last4", sa.String(length=4), nullable=False),
    )
    op.add_column(
        "subscription_payment",
        sa.Column("card_exp_month", sa.Integer(), nullable=False),
    )
    op.add_column(
        "subscription_payment", sa.Column("card_exp_year", sa.Integer(), nullable=False)
    )
    op.add_column(
        "subscription_payment",
        sa.Column("cardholder_name", sa.String(length=255), nullable=False),
    )
    op.add_column(
        "subscription_payment",
        sa.Column("cardholder_email", sa.String(length=255), nullable=False),
    )
    op.add_column(
        "subscription_payment", sa.Column("standalone", sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscription_payment", "standalone")
    op.drop_column("subscription_payment", "cardholder_email")
    op.drop_column("subscription_payment", "cardholder_name")
    op.drop_column("subscription_payment", "card_exp_year")
    op.drop_column("subscription_payment", "card_exp_month")
    op.drop_column("subscription_payment", "card_last4")
    op.drop_column("subscription_payment", "card_brand")
    # ### end Alembic commands ###
