"""added deleted_by and owner_id

Revision ID: a5230adcae73
Revises: de6b0bedac2d
Create Date: 2024-03-16 16:06:09.684618

"""
import uuid
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a5230adcae73"
down_revision: Union[str, None] = "de6b0bedac2d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project", sa.Column("owner_id", sa.UUID(), nullable=True))
    op.add_column("project", sa.Column("deleted_by", sa.UUID(), nullable=True))
    project = sa.table("project", sa.column("owner_id", sa.UUID))
    op.execute(project.update().values({"owner_id": uuid.uuid4()}))
    op.alter_column("project", "owner_id", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "deleted_by")
    op.drop_column("project", "owner_id")
    # ### end Alembic commands ###
