"""add default column to payment method

Revision ID: a9c797996f0c
Revises: f4fe29571ef5
Create Date: 2024-05-08 12:20:58.377754

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a9c797996f0c"
down_revision: Union[str, None] = "f4fe29571ef5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payment_method",
        sa.Column("default", sa.Boolean(), nullable=True, default=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("payment_method", "default")
    # ### end Alembic commands ###
