"""Add deleted by column to virtual lab

Revision ID: aa81eeb4dad6
Revises: 9a570c813370
Create Date: 2024-05-01 15:50:52.065166

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "aa81eeb4dad6"
down_revision: Union[str, None] = "9a570c813370"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("virtual_lab", sa.Column("deleted_by", sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("virtual_lab", "deleted_by")
    # ### end Alembic commands ###
