"""add_is_dropped_to_project

Revision ID: ae20bcced8c2
Revises: c5ac9c9b45be
Create Date: 2026-06-09 23:00:36.597174

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ae20bcced8c2"
down_revision: Union[str, None] = "c5ac9c9b45be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project",
        sa.Column("is_dropped", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "is_dropped")
    # ### end Alembic commands ###
