"""separate code attempts verif_gene

Revision ID: af66fe4cb028
Revises: 8830da6ee3a3
Create Date: 2025-02-15 17:38:27.591813

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "af66fe4cb028"
down_revision: Union[str, None] = "8830da6ee3a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "email_verification_codes",
        sa.Column("generation_attempts", sa.Integer(), nullable=False),
    )
    op.add_column(
        "email_verification_codes",
        sa.Column("verification_attempts", sa.Integer(), nullable=False),
    )
    op.drop_column("email_verification_codes", "attempts")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "email_verification_codes",
        sa.Column("attempts", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_column("email_verification_codes", "verification_attempts")
    op.drop_column("email_verification_codes", "generation_attempts")
    # ### end Alembic commands ###
