"""add subscription

Revision ID: b17497804775
Revises: e9833a2adbf6
Create Date: 2025-03-01 13:22:37.849669

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b17497804775"
down_revision: Union[str, None] = "e9833a2adbf6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscription",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("virtual_lab_id", sa.UUID(), nullable=False),
        sa.Column("stripe_subscription_id", sa.String(length=255), nullable=False),
        sa.Column("stripe_price_id", sa.String(length=255), nullable=False),
        sa.Column("customer_id", sa.String(length=255), nullable=False),
        sa.Column("current_period_start", sa.DateTime(), nullable=False),
        sa.Column("current_period_end", sa.DateTime(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "PAST_DUE",
                "UNPAID",
                "CANCELED",
                "INCOMPLETE",
                "INCOMPLETE_EXPIRED",
                "PAUSED",
                name="subscriptionstatus",
            ),
            nullable=False,
        ),
        sa.Column("cancel_at_period_end", sa.Boolean(), nullable=False),
        sa.Column("canceled_at", sa.DateTime(), nullable=True),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("billing_cycle_anchor", sa.DateTime(), nullable=True),
        sa.Column("default_payment_method", sa.String(length=255), nullable=True),
        sa.Column("latest_invoice", sa.String(length=255), nullable=True),
        sa.Column("auto_renew", sa.Boolean(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("interval", sa.String(length=50), nullable=False),
        sa.Column("stripe_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["virtual_lab_id"],
            ["virtual_lab.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_subscription_customer_id"),
        "subscription",
        ["customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subscription_status"), "subscription", ["status"], unique=False
    )
    op.create_index(
        "ix_subscription_status_period_end",
        "subscription",
        ["status", "current_period_end"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subscription_stripe_subscription_id"),
        "subscription",
        ["stripe_subscription_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_subscription_user_id"), "subscription", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_subscription_virtual_lab_id"),
        "subscription",
        ["virtual_lab_id"],
        unique=False,
    )
    op.create_table(
        "subscription_payment",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("subscription_id", sa.UUID(), nullable=False),
        sa.Column("stripe_invoice_id", sa.String(length=255), nullable=True),
        sa.Column("stripe_payment_intent_id", sa.String(length=255), nullable=False),
        sa.Column("stripe_charge_id", sa.String(length=255), nullable=True),
        sa.Column("amount_paid", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "SUCCEEDED",
                "PENDING",
                "FAILED",
                "REFUNDED",
                "PARTIALLY_REFUNDED",
                name="paymentstatus",
            ),
            nullable=False,
        ),
        sa.Column("period_start", sa.DateTime(), nullable=False),
        sa.Column("period_end", sa.DateTime(), nullable=False),
        sa.Column("payment_date", sa.DateTime(), nullable=False),
        sa.Column("invoice_pdf", sa.String(length=255), nullable=True),
        sa.Column("receipt_url", sa.String(length=255), nullable=True),
        sa.Column("stripe_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscription.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_subscription_payment_status"),
        "subscription_payment",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subscription_payment_stripe_invoice_id"),
        "subscription_payment",
        ["stripe_invoice_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subscription_payment_stripe_payment_intent_id"),
        "subscription_payment",
        ["stripe_payment_intent_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_subscription_payment_subscription_id"),
        "subscription_payment",
        ["subscription_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_subscription_payment_subscription_id"),
        table_name="subscription_payment",
    )
    op.drop_index(
        op.f("ix_subscription_payment_stripe_payment_intent_id"),
        table_name="subscription_payment",
    )
    op.drop_index(
        op.f("ix_subscription_payment_stripe_invoice_id"),
        table_name="subscription_payment",
    )
    op.drop_index(
        op.f("ix_subscription_payment_status"), table_name="subscription_payment"
    )
    op.drop_table("subscription_payment")
    op.drop_index(op.f("ix_subscription_virtual_lab_id"), table_name="subscription")
    op.drop_index(op.f("ix_subscription_user_id"), table_name="subscription")
    op.drop_index(
        op.f("ix_subscription_stripe_subscription_id"), table_name="subscription"
    )
    op.drop_index("ix_subscription_status_period_end", table_name="subscription")
    op.drop_index(op.f("ix_subscription_status"), table_name="subscription")
    op.drop_index(op.f("ix_subscription_customer_id"), table_name="subscription")
    op.drop_table("subscription")
    # ### end Alembic commands ###
