"""add entity id to bookmark

Revision ID: b21a2d089147
Revises: cb970364cd2a
Create Date: 2025-04-11 17:25:00.028614

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b21a2d089147"
down_revision: Union[str, None] = "cb970364cd2a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add entity_id as nullable first to avoid integrity errors with existing data
    op.add_column("bookmark", sa.Column("entity_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_bookmark_entity_id"), "bookmark", ["entity_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_bookmark_entity_id"), table_name="bookmark")
    op.drop_column("bookmark", "entity_id")
    # ### end Alembic commands ###
