"""make_institution_id_non_nullable

Revision ID: b873d0dbb15f
Revises: 255e7314d211
Create Date: 2026-06-06 19:33:59.046241

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b873d0dbb15f"
down_revision: Union[str, None] = "255e7314d211"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Backfill any courses with NULL institution_id to use Open Brain Institute
    op.execute(
        sa.text("""
            UPDATE course
            SET institution_id = (
                SELECT i.id FROM institution i WHERE i.name = 'Open Brain Institute'
            )
            WHERE institution_id IS NULL
        """)
    )

    op.alter_column("course", "institution_id", existing_type=sa.UUID(), nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("course", "institution_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###
