"""make resourceid for bookmark optional

Revision ID: b8b9e181e3b6
Revises: 6517ad801bf6
Create Date: 2025-05-06 10:46:51.952634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8b9e181e3b6'
down_revision: Union[str, None] = '6517ad801bf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookmark', 'resource_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('subscription', 'source')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('source', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.alter_column('bookmark', 'resource_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
