"""add student email to project

Revision ID: b9047317ad65
Revises: 7638e5e2a43f
Create Date: 2026-04-08 11:03:06.427560

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b9047317ad65"
down_revision: Union[str, None] = "7638e5e2a43f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project", sa.Column("contact_email", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "contact_email")
    # ### end Alembic commands ###
