"""add_unique_constraint_on_template_project_id

Revision ID: c0553f21e6f4
Revises: db64441b1c8b
Create Date: 2026-06-07 09:35:57.386781

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "c0553f21e6f4"
down_revision: Union[str, None] = "db64441b1c8b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_course_template_project_id"), table_name="course")
    op.create_index(
        op.f("ix_course_template_project_id"),
        "course",
        ["template_project_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_course_template_project_id"), table_name="course")
    op.create_index(
        op.f("ix_course_template_project_id"),
        "course",
        ["template_project_id"],
        unique=False,
    )
    # ### end Alembic commands ###
