"""add unique constraint on institution name

Revision ID: c15c48abebf3
Revises: 893e89bd925b
Create Date: 2026-06-05 12:33:57.818874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c15c48abebf3'
down_revision: Union[str, None] = '893e89bd925b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_institution_name'), table_name='institution')
    op.create_index(op.f('ix_institution_name'), 'institution', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_institution_name'), table_name='institution')
    op.create_index(op.f('ix_institution_name'), 'institution', ['name'], unique=False)
    # ### end Alembic commands ###
