"""Make bookmark.project_id non-nullable

Revision ID: c615148b3cf7
Revises: 551e7395c078
Create Date: 2025-10-29 20:38:18.616654

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c615148b3cf7"
down_revision: Union[str, None] = "551e7395c078"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("bookmark", "project_id", existing_type=sa.UUID(), nullable=False)
    op.create_index(
        op.f("ix_bookmark_category"), "bookmark", ["category"], unique=False
    )
    op.alter_column(
        "project_invite", "project_id", existing_type=sa.UUID(), nullable=False
    )
    op.alter_column(
        "virtual_lab_invite", "virtual_lab_id", existing_type=sa.UUID(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "virtual_lab_invite", "virtual_lab_id", existing_type=sa.UUID(), nullable=True
    )
    op.alter_column(
        "project_invite", "project_id", existing_type=sa.UUID(), nullable=True
    )
    op.drop_index(op.f("ix_bookmark_category"), table_name="bookmark")
    op.alter_column("bookmark", "project_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###
