"""remove budget and plan from vlab models

Revision ID: c710529aca8c
Revises: e9833a2adbf6
Create Date: 2024-02-21 12:34:56.789012

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c710529aca8c"
down_revision: Union[str, None] = "e9833a2adbf6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First ensure the budget_amount column exists and has a default value
    op.execute("UPDATE virtual_lab SET budget_amount = 0 WHERE budget_amount IS NULL")

    # Then drop the columns
    with op.batch_alter_table("virtual_lab") as batch_op:
        batch_op.drop_column("budget_amount")
        batch_op.drop_column("plan_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("virtual_lab") as batch_op:
        batch_op.add_column(sa.Column("plan_id", sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column("budget_amount", sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
