"""add stripe events to paid subscription and payments

Revision ID: cb69e5f593db
Revises: 62216ef51974
Create Date: 2025-03-17 09:05:00.811758

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cb69e5f593db"
down_revision: Union[str, None] = "62216ef51974"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "paid_subscription", sa.Column("stripe_event", sa.JSON(), nullable=True)
    )
    op.add_column(
        "subscription_payment", sa.Column("stripe_event", sa.JSON(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscription_payment", "stripe_event")
    op.drop_column("paid_subscription", "stripe_event")
    # ### end Alembic commands ###
