"""added update_at to project_star

Revision ID: de6b0bedac2d
Revises: 0e8c813d2693
Create Date: 2024-03-15 21:04:32.551882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "de6b0bedac2d"
down_revision: Union[str, None] = "0e8c813d2693"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project_star", sa.Column("updated_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project_star", "updated_at")
    # ### end Alembic commands ###
