"""add_budget_amount_and_vlab_topup

Revision ID: dea5531bc9dc
Revises: f4fe29571ef5
Create Date: 2024-05-13 12:02:41.689795

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.orm import Session

from alembic import op
from virtual_labs.infrastructure.db.models import VirtualLab

# revision identifiers, used by Alembic.
revision: str = "dea5531bc9dc"
down_revision: Union[str, None] = "f4fe29571ef5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    session = Session(bind=conn)
    op.create_table(
        "virtual_lab_topup",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("virtual_lab_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("stripe_event_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["virtual_lab_id"],
            ["virtual_lab.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "virtual_lab", sa.Column("budget_amount", sa.Integer(), nullable=True)
    )
    session.execute(statement=sa.update(VirtualLab).values(budget_amount=0))
    session.commit()
    op.alter_column(
        table_name="virtual_lab", column_name="budget_amount", nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("virtual_lab", "budget_amount")
    op.drop_table("virtual_lab_topup")
    # ### end Alembic commands ###
