"""add default constraint

Revision ID: e23d19504702
Revises: a9c797996f0c
Create Date: 2024-05-13 10:36:21.995083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e23d19504702"
down_revision: Union[str, None] = "a9c797996f0c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_default_payment_per_lab",
        "payment_method",
        ["virtual_lab_id", "default"],
        unique=True,
        postgresql_where=sa.text('"default" IS true'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_default_payment_per_lab",
        table_name="payment_method",
        postgresql_where=sa.text('"default" IS true'),
    )
    # ### end Alembic commands ###
