"""add courses

Revision ID: e7ca4990c359
Revises: 96c83d63c85e
Create Date: 2026-06-25 20:39:07.785443

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e7ca4990c359"
down_revision: Union[str, None] = "96c83d63c85e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "institution",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("name", sa.String(length=250), nullable=False),
        sa.Column("contact_email", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_institution_name"), "institution", ["name"], unique=True)

    # Seed Open Brain Institute
    op.execute(
        sa.text("""
            INSERT INTO institution (id, name, contact_email, created_at, updated_at)
            VALUES (
                gen_random_uuid(),
                'Open Brain Institute',
                'obi-virtual-lab@openbraininstitute.org',
                now(),
                now()
            )
        """)
    )

    op.create_table(
        "course",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("virtual_lab_id", sa.UUID(), nullable=False),
        sa.Column("institution_id", sa.UUID(), nullable=False),
        sa.Column("template_project_id", sa.UUID(), nullable=False),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_drop_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "ACTIVE", "VOIDED", name="coursestatus"),
            nullable=False,
        ),
        sa.Column("credits_per_seat", sa.Integer(), nullable=False),
        sa.Column(
            "budget_depleted", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institution.id"],
        ),
        sa.ForeignKeyConstraint(
            ["template_project_id"],
            ["project.id"],
        ),
        sa.ForeignKeyConstraint(
            ["virtual_lab_id"],
            ["virtual_lab.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_course_end_date"), "course", ["end_date"], unique=False)
    op.create_index(
        op.f("ix_course_institution_id"), "course", ["institution_id"], unique=False
    )
    op.create_index(op.f("ix_course_status"), "course", ["status"], unique=False)
    op.create_index(
        op.f("ix_course_template_project_id"),
        "course",
        ["template_project_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_course_virtual_lab_id"), "course", ["virtual_lab_id"], unique=True
    )
    op.create_table(
        "course_enrolment",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("course_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("contact_email", sa.String(length=255), nullable=False),
        sa.Column("student_id", sa.String(length=255), nullable=False),
        sa.Column("claimed_by", sa.UUID(), nullable=True),
        sa.Column("is_dropped", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["course.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "course_id", "contact_email", name="uq_enrolment_course_email"
        ),
        sa.UniqueConstraint(
            "course_id", "student_id", name="uq_enrolment_course_student_id"
        ),
        sa.UniqueConstraint("project_id"),
    )
    op.create_index(
        op.f("ix_course_enrolment_claimed_by"),
        "course_enrolment",
        ["claimed_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_course_enrolment_course_id"),
        "course_enrolment",
        ["course_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_course_enrolment_is_dropped"),
        "course_enrolment",
        ["is_dropped"],
        unique=False,
    )
    op.create_table(
        "seat",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("course_id", sa.UUID(), nullable=False),
        sa.Column("institution_id", sa.UUID(), nullable=False),
        sa.Column("is_consumed", sa.Boolean(), nullable=False),
        sa.Column(
            "previously_dropped", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("batch_id", sa.UUID(), nullable=False),
        sa.Column("enrolment_id", sa.UUID(), nullable=True),
        sa.Column("expiry_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("credit_value", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["course.id"],
        ),
        sa.ForeignKeyConstraint(
            ["enrolment_id"],
            ["course_enrolment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institution.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("enrolment_id"),
    )
    op.create_index(op.f("ix_seat_batch_id"), "seat", ["batch_id"], unique=False)
    op.create_index(op.f("ix_seat_course_id"), "seat", ["course_id"], unique=False)
    op.drop_column("project", "contact_email")

    # Migrate existing virtual labs with course_template_project_id into course table
    op.execute(
        sa.text("""
            INSERT INTO course (id, virtual_lab_id, institution_id, template_project_id, status, credits_per_seat, created_at, updated_at)
            SELECT
                gen_random_uuid(),
                vl.id,
                (SELECT i.id FROM institution i WHERE i.name = 'Open Brain Institute'),
                vl.course_template_project_id,
                'DRAFT',
                0,
                now(),
                now()
            FROM virtual_lab vl
            WHERE vl.course_template_project_id IS NOT NULL
        """)
    )

    op.drop_column("virtual_lab", "course_template_project_id")
    op.drop_column("virtual_lab", "is_course_initialized")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "virtual_lab",
        sa.Column(
            "is_course_initialized",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "virtual_lab",
        sa.Column(
            "course_template_project_id", sa.UUID(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "project",
        sa.Column(
            "contact_email", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
    )

    # Migrate data back from course table to virtual_lab
    op.execute(
        sa.text("""
            UPDATE virtual_lab
            SET course_template_project_id = c.template_project_id
            FROM course c
            WHERE c.virtual_lab_id = virtual_lab.id
        """)
    )
    op.drop_index(op.f("ix_seat_course_id"), table_name="seat")
    op.drop_index(op.f("ix_seat_batch_id"), table_name="seat")
    op.drop_table("seat")
    op.drop_index(op.f("ix_course_enrolment_is_dropped"), table_name="course_enrolment")
    op.drop_index(op.f("ix_course_enrolment_course_id"), table_name="course_enrolment")
    op.drop_index(op.f("ix_course_enrolment_claimed_by"), table_name="course_enrolment")
    op.drop_table("course_enrolment")
    op.drop_index(op.f("ix_course_virtual_lab_id"), table_name="course")
    op.drop_index(op.f("ix_course_template_project_id"), table_name="course")
    op.drop_index(op.f("ix_course_status"), table_name="course")
    op.drop_index(op.f("ix_course_institution_id"), table_name="course")
    op.drop_index(op.f("ix_course_end_date"), table_name="course")
    op.drop_table("course")
    sa.Enum(name="coursestatus").drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f("ix_institution_name"), table_name="institution")
    op.drop_table("institution")
    # ### end Alembic commands ###
