"""remove attempts columns

Revision ID: e9833a2adbf6
Revises: af66fe4cb028
Create Date: 2025-02-27 13:04:53.649641

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e9833a2adbf6"
down_revision: Union[str, None] = "af66fe4cb028"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("email_verification_codes", "locked_until")
    op.drop_column("email_verification_codes", "verification_attempts")
    op.drop_column("email_verification_codes", "generation_attempts")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "email_verification_codes",
        sa.Column(
            "generation_attempts", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "email_verification_codes",
        sa.Column(
            "verification_attempts", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "email_verification_codes",
        sa.Column(
            "locked_until", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
