"""remove email verification code table

Revision ID: ee06c49abcad
Revises: fb3b9c8c3662
Create Date: 2026-03-18 19:32:45.485727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee06c49abcad'
down_revision: Union[str, None] = 'fb3b9c8c3662'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_verification_codes_code'), table_name='email_verification_codes')
    op.drop_index(op.f('ix_email_verification_codes_email'), table_name='email_verification_codes')
    op.drop_index(op.f('ix_verification_codes_compound_properties'), table_name='email_verification_codes')
    op.drop_index(op.f('ix_verification_codes_created_at'), table_name='email_verification_codes')
    op.drop_table('email_verification_codes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verification_codes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('virtual_lab_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=6), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('verified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('virtual_lab_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.CheckConstraint("code::text ~* '^[0-9]{6}$'::text", name=op.f('valid_code_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('email_verification_codes_pkey'))
    )
    op.create_index(op.f('ix_verification_codes_created_at'), 'email_verification_codes', ['created_at'], unique=False)
    op.create_index(op.f('ix_verification_codes_compound_properties'), 'email_verification_codes', ['email', 'code', 'virtual_lab_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_email_verification_codes_email'), 'email_verification_codes', ['email'], unique=False)
    op.create_index(op.f('ix_email_verification_codes_code'), 'email_verification_codes', ['code'], unique=False)
    # ### end Alembic commands ###
