"""remove uniquness for payement intent

Revision ID: eed2b128495f
Revises: b17497804775
Create Date: 2025-03-04 17:55:35.351413

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eed2b128495f"
down_revision: Union[str, None] = "b17497804775"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_subscription_payment_stripe_payment_intent_id",
        table_name="subscription_payment",
    )
    op.drop_constraint(
        "virtual_lab_stripe_customer_id_unique", "virtual_lab", type_="unique"
    )
    op.create_index(
        op.f("ix_virtual_lab_stripe_customer_id"),
        "virtual_lab",
        ["stripe_customer_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_virtual_lab_stripe_customer_id"), table_name="virtual_lab")
    op.create_unique_constraint(
        "virtual_lab_stripe_customer_id_unique", "virtual_lab", ["stripe_customer_id"]
    )
    op.create_index(
        "ix_subscription_payment_stripe_payment_intent_id",
        "subscription_payment",
        ["stripe_payment_intent_id"],
        unique=True,
    )
    # ### end Alembic commands ###
