"""add index to foreign keys

Revision ID: f7446c78a705
Revises: 69985dd88e88
Create Date: 2024-05-23 14:15:43.915944

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "f7446c78a705"
down_revision: Union[str, None] = "69985dd88e88"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_payment_method_virtual_lab_id"),
        "payment_method",
        ["virtual_lab_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_virtual_lab_id"), "project", ["virtual_lab_id"], unique=False
    )
    op.create_index(
        op.f("ix_project_invite_project_id"),
        "project_invite",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_star_project_id"), "project_star", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_virtual_lab_invite_virtual_lab_id"),
        "virtual_lab_invite",
        ["virtual_lab_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_virtual_lab_topup_virtual_lab_id"),
        "virtual_lab_topup",
        ["virtual_lab_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_virtual_lab_topup_virtual_lab_id"), table_name="virtual_lab_topup"
    )
    op.drop_index(
        op.f("ix_virtual_lab_invite_virtual_lab_id"), table_name="virtual_lab_invite"
    )
    op.drop_index(op.f("ix_project_star_project_id"), table_name="project_star")
    op.drop_index(op.f("ix_project_invite_project_id"), table_name="project_invite")
    op.drop_index(op.f("ix_project_virtual_lab_id"), table_name="project")
    op.drop_index(op.f("ix_payment_method_virtual_lab_id"), table_name="payment_method")
    # ### end Alembic commands ###
