"""update virtual_lab table with email_verified

Revision ID: fb3b9c8c3662
Revises: 2192a5aa8ba6
Create Date: 2026-03-17 10:47:52.267260

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fb3b9c8c3662"
down_revision: Union[str, None] = "2192a5aa8ba6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "email_verification_codes",
        sa.Column("virtual_lab_id", sa.UUID(), nullable=False),
    )
    op.alter_column(
        "email_verification_codes",
        "virtual_lab_name",
        existing_type=sa.VARCHAR(length=255),
        nullable=True,
    )
    op.drop_index(
        op.f("ix_verification_codes_compound_properties"),
        table_name="email_verification_codes",
    )
    op.create_index(
        "ix_verification_codes_compound_properties",
        "email_verification_codes",
        ["email", "code", "virtual_lab_id", "user_id"],
        unique=False,
    )
    op.add_column(
        "virtual_lab", sa.Column("email_verified", sa.Boolean(), nullable=True)
    )
    op.execute(
        "UPDATE virtual_lab SET email_verified = CASE WHEN reference_email IS NOT NULL AND reference_email != '' THEN TRUE ELSE FALSE END"
    )
    op.alter_column("virtual_lab", "email_verified", nullable=False)
    op.create_index(
        op.f("ix_virtual_lab_email_verified"),
        "virtual_lab",
        ["email_verified"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_virtual_lab_email_verified"), table_name="virtual_lab")
    op.drop_column("virtual_lab", "email_verified")
    op.drop_index(
        "ix_verification_codes_compound_properties",
        table_name="email_verification_codes",
    )
    op.create_index(
        op.f("ix_verification_codes_compound_properties"),
        "email_verification_codes",
        ["email", "code", "virtual_lab_name", "user_id"],
        unique=False,
    )
    op.alter_column(
        "email_verification_codes",
        "virtual_lab_name",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
    )
    op.drop_column("email_verification_codes", "virtual_lab_id")
    # ### end Alembic commands ###
