"""replace_virtual_lab_id_with_course_id_on_seat

Revision ID: ff9173c91b7c
Revises: 7fcbd62c09db
Create Date: 2026-06-08 21:24:20.949895

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ff9173c91b7c"
down_revision: Union[str, None] = "7fcbd62c09db"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("seat", sa.Column("course_id", sa.UUID(), nullable=False))
    op.drop_constraint(op.f("seat_virtual_lab_id_fkey"), "seat", type_="foreignkey")
    op.create_foreign_key(None, "seat", "course", ["course_id"], ["id"])
    op.drop_column("seat", "virtual_lab_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "seat",
        sa.Column("virtual_lab_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "seat", type_="foreignkey")
    op.create_foreign_key(
        op.f("seat_virtual_lab_id_fkey"),
        "seat",
        "virtual_lab",
        ["virtual_lab_id"],
        ["id"],
    )
    op.drop_column("seat", "course_id")
    # ### end Alembic commands ###
