name: publish-production-image-ecr

on:
    push:
      branches:
        - main

permissions:
  contents: write
  id-token: write
  actions: write

jobs:
  publish-to-aws-ecr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0 # Get full history to check existing tags

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Determine new tag
        id: tag
        run: |
          YEAR=$(date +'%Y')
          MONTH=$(date +'%m')
          DAY=$(date +'%d')
          LATEST_TAG=$(git tag --sort=-v:refname | grep -E "^${YEAR}\.${MONTH}\.${DAY}\.[0-9]+$" | head -n 1 || echo "")

          if [[ -z "$LATEST_TAG" ]]; then
            COUNTER=1
          else
            COUNTER=$(( ${LATEST_TAG##*.} + 1 ))
          fi

          NEW_TAG="${YEAR}.${MONTH}.${DAY}.${COUNTER}"
          echo "NEW_TAG=${NEW_TAG}" >> $GITHUB_ENV
          echo "New tag: $NEW_TAG"

      - name: Create Git Tag
        run: |
          git tag $NEW_TAG
          git push origin $NEW_TAG

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::985539765147:role/gh_ecr_push_virtual-lab-api
          aws-region: us-east-1

      - name: Authenticate with AWS Public ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ vars.PUBLICECR_URI }}:${{ env.NEW_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
