name: Pre-merge Review

on: [pull_request]

jobs:
  pull-request-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install poetry && poetry sync
      - name: Run styling
        run: make style-check
      - name: Run type checks
        run: make type-check
      - name: Start services
        run: IS_CI="True" make init
      - name: Check migration scripts are added for modified schemas
        run: make check-db-schema
      - name: Run tests
        env:
          TEST_STRIPE_SECRET_KEY: ${{ secrets.TEST_STRIPE_SECRET_KEY }}
        run: |
          echo STRIPE_SECRET_KEY=${{ secrets.TEST_STRIPE_SECRET_KEY }} >> .env.local
          echo STRIPE_DEVICE_NAME=CI >> .env.local
          DEPLOYMENT_ENV=testing  poetry run pytest
      - name: cleanup
        if: ${{ always() }}
        run: |
          docker compose -f env-prep/docker-compose-dev.yml -p vlm-project down --rmi all --volumes
          docker system prune --force --volumes
